### ISSUE TITLE
bug: some file have new revision since last synchronisation but no modification done one file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/trsync#60]
## At present

I have tested synchronisation on Windows and all seems working good. But now in tracim, I can seen some file where new revision exist, but I don't do any change on it. 

before using trsync the date of last revision is 14/02/2019, but now I have a new revision. So some file is show in recent activities and I don't have solution to understand what is the difference between oldest revision and the last one.

## Expected

- not create a new revision if nothing change on file.

**Comment by buxx** [comment]
Very probably a trsync error about "local update"

**Comment by buxx** [comment]
I can't find a reproduction steps and cannot understand how trsync algorithm can detect false changes. Recent added logs show coherent timestamp changes about uploaded files.

@PhilippeAccorsi @Skylsmoi Can you look about your trsync logs and search lines with `disk timestamp=` pattern which concern "wrong uploaded files" ? Things like : 

    juil. 10 17:51:32 P21BSL trsync.desktop[23769]: [2022-07-10T15:51:32Z INFO  trsync::local] [tracim.bux.fr::3] File '"Cours/Rust"' has been modified (disk timestamp='1657466473946' != db timestamp='1649928630557')

@PhilippeAccorsi @Skylsmoi Did you notice this behavior on Windows too or only on GNU/Linux system ?

My new approach is to consider files are really "new", from the point of view of file disk modified timestamp. @PhilippeAccorsi Do you know if something on operating system (Windows & GNU/Linux) can modify the "modified" timestamp without user action ?

A possible bypassing is to add the https://github.com/tracim/tracim/issues/5553 Tracim feature to interrupt upload when it is useless (because same file content). @lebouquetin what do you think about this ? I can propose Tracim update in this way.

**Comment by Skylsmoi** [comment]
I have only seen this issue on my first windows test

**Comment by buxx** [comment]
:warning: Bug origin found : TrSync look at files and folders last modified date to determine if it is updated. But when modify a file, all parent's folders are "last modified date" updated !

**Comment by buxx** [comment]
Behavior confirmed. Possible solution : At TrSync startup, don't look at folder date change : If something change, it can only be the name, so date is not useful.

**Comment by lebouquetin** [comment]
@buxx do you're change detection rely on the inode number ? For example, if a folder has been renamed while the sync client was off, the rename will be identified?

**Comment by buxx** [comment]
@lebouquetin haha you're on my mind : I think about that during my sleep ^^

About the current issue bug, drop the modification date is enough. But to identify folder renaming, inode identification will be very useful. Note using inode is not secured, they can be completely different in case of data moving (like on other partition), so we must use them only to try to identify folder renaming.

**Comment by lebouquetin** [comment]
I remember the [thread on LinuxFR about inode-based tracking](https://linuxfr.org/users/bux-2/journaux/trsync-un-outil-de-synchronisation-bidirectionnelle-pour-travailler-hors-ligne-avec-tracim#comment-1867978) ...

**Comment by buxx** [comment]
Good point. The [Bruno Michel](https://linuxfr.org/users/nono) [example](https://linuxfr.org/users/bux-2/journaux/trsync-un-outil-de-synchronisation-bidirectionnelle-pour-travailler-hors-ligne-avec-tracim#comment-1867978) seems to stop the inode idea for the folder rename :(
